feat : add Popover
Drill4J/ui-kit pull request #163
Opened 2021-11-16 09:41 UTC by IliaSolovev

2021-11-16 14:24 UTC, RomanAchilov requested changes

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/forms/inputs/dropdown/dropdown.tsx
> +                      tw="flex items-center pl-2 pr-8 text-monochrome-black text-14 leading-32 hover:bg-monochrome-light-tint"
different paddings from design?

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/menu/menu.tsx
> +        <>
useless React.Fragment

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/menu/menu.tsx
> +                style={{
it doesn't look good

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/menu/menu.tsx
>    label: string;
we have a mandatory Label, although we can pass Content

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/popover/popover.tsx
> +export const Popover = ({
👍

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/table/pagination.tsx
> +  const Ellipsis = () => (
lit looks great

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/tooltip/tooltip.tsx
> +      setTooltipPositionType(entry.intersectionRect.left ? 'top-left' : 'top-right');
what if you need an intersection from below or from above?

2021-11-16 14:24 UTC, RomanAchilov commented on src/components/tooltip/tooltip.tsx
> +        bottom: -8px;
Easy refactoring with TW jit

2021-11-16 14:24 UTC, RomanAchilov commented on src/hooks/use-intersection-side.tsx
> +export interface Props {
u didn't use it

2021-11-18 10:49 UTC, IliaSolovev commented on src/components/menu/menu.tsx
>    label: string;
Content it is wrapper over the label

2021-11-18 10:50 UTC, merged