EPMDJ-9248: Add render props for headers
Drill4J/ui-kit pull request #172
Opened 2021-12-10 09:16 UTC by dmitrii-kliushentsev

2021-12-10 10:09 UTC, RomanAchilov requested changes

2021-12-10 10:09 UTC, RomanAchilov commented on src/components/table/table.tsx
>    name?: string;
?

2021-12-10 10:09 UTC, RomanAchilov commented on src/components/table/table.tsx
>    resultName?: string;
?

2021-12-10 10:09 UTC, RomanAchilov commented on src/components/table/table.tsx
> +  header?: (title: string, pagesLength: number, dataLength: number) => JSX.Element;
renderHeader

2021-12-10 10:09 UTC, RomanAchilov commented on src/components/table/table.tsx
> +      {header(name, page.length, data.length)}
```suggestion
      {renderHeader(page.length, data.length)}
```

2021-12-14 08:44 UTC, IliaSolovev approved these changes

2021-12-14 08:44 UTC, IliaSolovev commented on src/components/table/table.tsx
> +      {renderHeader && renderHeader(page.length, data.length)}
It must be one argument because it is a component

2021-12-14 11:16 UTC, merged