EPMDJ-9407: Refactor Portal component
Drill4J/ui-kit pull request #181
Opened 2021-12-19 16:42 UTC by dmitrii-kliushentsev

2021-12-20 06:41 UTC, IliaSolovev commented on src/components/portal/portal.tsx
> +  }, [element]);
```suggestion
  }, [rootElementById]);
```

2021-12-20 09:51 UTC, RomanAchilov commented on src/components/portal/portal.tsx
> +  const rootElementById = document.getElementById(rootElementId);
in a good way, the creation of the handler should take place inside useEffect

2021-12-20 09:54 UTC, RomanAchilov requested changes

2021-12-20 09:54 UTC, RomanAchilov commented on src/components/portal/portal.tsx
> +  const rootElementById = document.getElementById(rootElementId);
https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily
check this

2021-12-23 10:18 UTC, IliaSolovev requested changes

2021-12-23 10:18 UTC, IliaSolovev commented on src/components/portal/portal.tsx
> +      rootElementById.appendChild(element);
```suggestion
      rootElementById?.appendChild(element);
```

2021-12-23 10:18 UTC, IliaSolovev commented on src/components/portal/portal.tsx
> +function createAndAppendElementWithId(id: string): HTMLDivElement {
```suggestion
function createAndAppendElement(id: string): HTMLDivElement {
```

2021-12-27 14:33 UTC, IliaSolovev approved these changes

2021-12-27 14:33 UTC, IliaSolovev commented on src/components/portal/portal.tsx
> +  ReactChild, ReactPortal, useEffect, useMemo,
remove unused vars

2021-12-27 17:19 UTC, merged