EPMDJ-9249: Decompose compound cell
Drill4J/ui-kit pull request #190
Opened 2021-12-29 02:56 UTC by dmitrii-kliushentsev

2021-12-29 06:40 UTC, IliaSolovev requested changes

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/forms/inputs/button/copy-button/copy-button.tsx
> +import { Icons } from '../../../../icon';
Alias?

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/forms/inputs/button/copy-button/copy-button.tsx
> +}
```suggestion
}

```

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/forms/inputs/button/copy-button/copy-button.tsx
> +export const CopyButton = ({ text }: Props) => {
As i remember we decide to use children here

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cellcomponents/name.tsx
> +  ${({ bold }: { bold: boolean }) => bold && tw`font-bold`}
we can set it inline without props

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cellcomponents/link.tsx
> +export const Link: FC = ({ children }) => (
We already have link styles

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cellcomponents/additional-info.tsx
> +    data-test="compound-cell:additional-info"
Why here you write compound cell if it is not a compound cell component?

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cellcomponents/index.ts
> +export const CellComponents = {
I know that this is a component, why note about it again

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cellcomponents/index.ts
> +  Link,
as I understand it all this is part of one component? so why are you creating different files for it?

2021-12-29 06:40 UTC, IliaSolovev commented on src/components/table/cells/compound-cell/compound-cell.tsx
> +    <div className="text-ellipsis group">
className?

2021-12-29 08:50 UTC, RomanAchilov requested changes
It is necessary to synchronize the cells with the design system. Make basic components -> make complex ones inside the main application and using tailwind styling. Also prepare hooks for complex logic.

2022-01-11 09:40 UTC, IliaSolovev approved these changes

2022-01-11 09:40 UTC, IliaSolovev commented on src/components/table/cells/compound-cell/compound-cell.tsx
> +          bold={!!cellAdditionalInfo}
```suggestion
          bold={Boolean(cellAdditionalInfo)}
```

2022-01-11 09:43 UTC, IliaSolovev approved these changes

2022-01-11 09:44 UTC, IliaSolovev approved these changes

2022-01-11 11:17 UTC, merged