EPMDJ-3047: Update Tooltip and Portal components
Drill4J/ui-kit pull request #41
Opened 2020-09-20 20:00 UTC by RomanAchilov

Issue: EPMDJ-3047

2020-09-25 13:35 UTC, pavyarov requested changes

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.module.scss
> +      &--top-center {
center

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.module.scss
> +      &--top-left {
left

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.module.scss
> +      &--top-right {
right

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.spec.tsx
> -  it('should render message at mouserover', () => {
?

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.stories.tsx
> +      <Tooltip message="TooltipTooltipTooltipTooltipTooltipTooltipTooltipTooltipTooltipTooltipTooltipTooltip">
lor

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const coords = messageRef?.current?.getBoundingClientRect() || undefined;
`|| undefined`

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  React.useEffect(() => {
```suggestion
  React.useLayoutEffect(() => {
```

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const topPosition = `${childrenTopPosition - messageHeight - triangularPointerSize - customTopOffset}px`;
create a function `getTooltipPosition`

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const topPosition = `${childrenTopPosition - messageHeight - triangularPointerSize - customTopOffset}px`;
dont forget to write tests

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const LeftRightPositionToogle = () => ({
```suggestion
  const togglePosition = () => ({
```

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const setTopCenterPosition = () => ({
i think this will be return value of `getTooltipPosition`

2020-09-25 13:35 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const [position, setPosition] = React.useState('top-center');
```suggestion
  const [position, setPosition] = React.useState('center');
```

2020-09-25 21:49 UTC, RomanAchilov commented on src/components/tooltip/tooltip.module.scss
> +    z-index: 100;
need for modal

2020-09-26 00:16 UTC, RomanAchilov commented on src/components/tooltip/tooltip.spec.tsx
> -  it('should render message at mouserover', () => {
there are difficulties with testing due to the use of "new IntersectionObserver"

2020-09-28 10:57 UTC, pavyarov requested changes

2020-09-28 10:57 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  customTopOffset?: number;
what the hell is it?)

2020-09-28 10:57 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +  const getTooltipPosition = () => {
tests?

2020-09-28 10:57 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +    switch (tooltipPositionType) {
tooltipPositionType argument

2020-09-28 10:57 UTC, pavyarov commented on src/components/tooltip/tooltip.tsx
> +            <div style={{ padding: '8px 16px' }} ref={messageRef}>
padding?

2020-11-09 14:37 UTC, pavyarov approved these changes

2020-11-09 14:37 UTC, merged