EPMDJ-4330: Fix console warning on Test2Code Page
Drill4J/ui-kit pull request #42
Opened 2020-09-25 07:40 UTC by SMPlay

2020-09-25 07:56 UTC, RomanAchilov requested changes
you need to increasethe version in package.json

2020-09-25 07:56 UTC, RomanAchilov commented on src/components/sort-arrows/sort-arrows.tsx
> +    <Wrapper>
SortArrowWrapper

2020-09-25 07:56 UTC, RomanAchilov commented on src/components/sort-arrows/sort-arrows.tsx
> +      <Arrow active={order === 'ASC'}>
mb SortArrowUp and SortArrowDown

2020-09-25 08:00 UTC, SMPlay commented on src/components/sort-arrows/sort-arrows.tsx
> +    <Wrapper>
Probably it's too much. I think this is clear from the context

2020-09-28 08:23 UTC, RomanAchilov approved these changes

2020-09-28 11:45 UTC, RomanAchilov requested changes
rename branch
rebase

2020-09-28 13:52 UTC, closed without merging