EPMDJ-3854 Update system and general alerts
Drill4J/ui-kit pull request #43
Opened 2020-09-25 07:40 UTC by IliaSolovev

2020-09-25 08:04 UTC, RomanAchilov requested changes

2020-09-25 08:04 UTC, RomanAchilov commented on .gitignore
> +.idea
:(

2020-09-25 08:04 UTC, RomanAchilov commented on src/components/message-panel/message-panel.module.scss
> +    font-weight: 600;
check style guide

2020-09-25 14:40 UTC, pavyarov requested changes

2020-09-25 14:40 UTC, pavyarov commented on .gitignore
> -
add empty line

2020-09-28 08:24 UTC, RomanAchilov approved these changes

2020-09-28 08:38 UTC, pavyarov approved these changes

2020-09-28 08:38 UTC, merged