EPMDJ-4840: Add tooltip into overflow-text component
Drill4J/ui-kit pull request #47
Opened 2020-10-08 19:42 UTC by IliaSolovev

Issue: EPMDJ-4840

2020-10-08 20:13 UTC, RomanAchilov requested changes

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +  const rootRef = React.useRef<HTMLDivElement>(null);
childrenRef

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +  const [isIntersecting, setIsIntersecting] = React.useState(true);
const [hint, setHint] = React.useState('');

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +      ([entry]) => setIsIntersecting(entry.isIntersecting),
([entry]) => !entry.isIntersecting && setHint(children),

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +  children: React.ReactNode | React.ReactNode[];
string

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +  tooltipText?: string;
delete

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +    childrenNode.current !== null && observer.observe(childrenNode.current);
childrenRef.current && observer.observe(childrenRef.current);

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +    <div className={className} ref={rootRef}>
delete ref={rootRef}

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +      <span ref={childrenNode} title={!isIntersecting ? tooltipText : ''}>{children}</span>
<span ref={messageRef} title={hint}>{children}</span>

2020-10-08 20:13 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.stories.tsx
> +    <OverflowText tooltipText="Overflow text">Overflow text Overflow text</OverflowText>
more examples Pls

2020-10-09 13:19 UTC, RomanAchilov requested changes
use data-title for styling

2020-10-09 13:19 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +import { BEM, span } from '@redneckz/react-bem-helper';
unused span

2020-10-13 10:56 UTC, RomanAchilov requested changes

2020-10-13 10:56 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +import * as React from 'react';
nice

2020-10-13 10:56 UTC, RomanAchilov commented on src/components/overflow-text/overflow-text.tsx
> +    <div className={className} data-title={hint || null}>
null?

2020-10-14 08:55 UTC, IliaSolovev commented on src/components/overflow-text/overflow-text.tsx
> +    <div className={className} data-title={hint || null}>
It need that when we pass there empty string we don`t see empty tooltip block with paddings

2020-10-14 13:23 UTC, closed without merging