EPMDJ-3753: rotate dropdown arrow on click
Drill4J/ui-kit pull request #52
Opened 2020-10-21 10:35 UTC by SMPlay

Issue: EPMDJ-3753

2020-10-21 18:00 UTC, RomanAchilov requested changes

2020-10-21 18:00 UTC, RomanAchilov commented on src/forms/inputs/dropdown/dropdown.module.scss
> +    padding-left: 9px;
incorrect
correct 4 8 12 16 ...

2020-10-21 18:01 UTC, RomanAchilov requested changes
ui kit version++

2020-10-22 11:45 UTC, RomanAchilov approved these changes

2020-10-22 18:04 UTC, pavyarov approved these changes

2020-10-22 18:04 UTC, merged