EPMDJ-6587: remove visibility sensor from menu component
Drill4J/ui-kit pull request #94
Opened 2021-04-12 10:10 UTC by IliaSolovev

Issue: EPMDJ-6587

2021-04-12 12:57 UTC, RomanAchilov approved these changes

2021-04-13 08:17 UTC, RomanDavlyatshin requested changes

2021-04-13 08:17 UTC, RomanDavlyatshin commented on src/components/menu/menu.tsx
> +              right: 'calc(50% - 22px)',
😒 magic numbers are not good

2021-04-13 08:17 UTC, RomanDavlyatshin commented on src/components/menu/menu.tsx
> +                    <ItemLabel>{content || label}</ItemLabel>
Didn't we want to get rid of BEM helper gradually? I suggest refactoring to ordinary <span> with utility classes

2021-04-13 14:28 UTC, IliaSolovev commented on src/components/menu/menu.tsx
> +  } = node?.current?.getBoundingClientRect() || {};
Yes, because menu `iconTopPosition`  used only that calc how display menu above or below the icon

2021-04-13 14:34 UTC, IliaSolovev commented on src/components/menu/menu.tsx
> +                    <ItemLabel>{content || label}</ItemLabel>
we don`t have utility classes here

2021-04-13 14:34 UTC, merged